### ISSUE TITLE
Does it work with Amazon S3 server provider?

### ISSUE THREAD

**Issue by abindalSchuco** [styletronix/cfapiSync#4]
I can see in the readme **Amazon S3** as planned, But just checking how far are you in that implementation, Can you give me any lead on that? I need it to work with S3.

**Comment by styletronix** [comment]
As the project is not on my schedule right now, I have no idea when the S3 implementation will be ready

**Comment by abindalSchuco** [comment]
Ok now worries, You have done a great work, and Thank you for your response.
