### ISSUE TITLE
Unable to sync files that are saved while file open. 

### ISSUE THREAD

**Issue by gashlin** [styletronix/cfapiSync#5]
I get an error that cannot create place holder when testing this. I open a AutoCAD drawing and it creates .dwl files. I wanted to test those syncing and they are in use so it does not create the place holder. Any idea where in the code this could be adjusted? I was thinking of a place to FORCE it to put the file back on the server regardless. It is a temp file so it will delete itself once file is closed.

I just started going through the code and so far this is great. I am curious to see if I can make some adjustments to contribute.

**Comment by styletronix** [comment]
I don't think it may be possible to sync the open file because og this is not the way the Windows 10 API works. It just can't replace the file with the placeholder while in use.
