### ISSUE TITLE
Exception: 'The file is not a cloud file'

### ISSUE THREAD

**Issue by csa89** [styletronix/cfapiSync#7]
Hi,

I encountered an issue while running the code to register a sync root using `StorageProviderSyncRootManager.Register(SyncRootInfo);` The exception thrown is:
`System.Exception: 'The file is not a cloud file. (Exception from HRESULT: 0x80070178)'`

**Steps Taken:**

    Verified that the folder exists and has the correct permissions.
    Ran the application with administrative privileges.

Have you encountered this error in your implementation? Any insights or suggestions to resolve this issue would be greatly appreciated.

Thank you

**Comment by styletronix** [comment]
Make sure the folder is on a NTFS drive. Did you manage to get any other folder working?

**Comment by csa89** [comment]
It worked directly on the C drive. At first, it worked using C:\Users\[my user]\VirtualTest, but after several retries, it stopped working and never worked again. Now, it only works using the C drive.
